apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
#These fields tell kustomize which resource its needs to apply configuration to
spec:
  template:
    spec:
      containers:
      - name: flask-app 
#tells kustomize which container to apply config to
        env:
        - name: DEBUG
          value: "true"